core/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.encrypt_url import urlEncryption, urlEncoding
from authentication.views import signin

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', signin, name='signin'),
    path(f"{urlEncryption('authentication')}{urlEncoding('authentication')}/", include('authentication.urls')),
    path(f"{urlEncryption('dashboard')}{urlEncoding('dashboard')}/", include('dashboard.urls')),    
]

dashboard/urls.py
from django.urls import path
from . views import *
from .encrypt_url import urlEncryption, urlEncoding

urlpatterns = [
    path(f"{urlEncryption('main')}{urlEncoding('main')}/", main, name='main'),
    path(f"{urlEncryption('new_post')}{urlEncoding('new_post')}/", newPost, name='new_post'),
    path(f"{urlEncryption('refresh')}{urlEncoding('refresh')}/<str:user_provided_id>/", refresh, name='refresh'),
    path(f"{urlEncryption('add_post')}{urlEncoding('add_post')}/<str:post_id>/", addPost, name='add_post'),
    path(f"{urlEncryption('new_post_manually')}{urlEncoding('new_post_manually')}", new_post_manually, name='new_post_manually'),
    path(f"{urlEncryption('edit_post')}{urlEncoding('edit_post')}/<str:post_id>/", editPost, name='edit_post'),
    path(f"{urlEncryption('delete_post')}{urlEncoding('delete_post')}/<str:post_id>/", deletePost, name='delete_post'),
    path(f"{urlEncryption('save_post')}{urlEncoding('save_post')}/<str:post_id>/", savePost, name='save_post'),
    path(f"{urlEncryption('post_details')}{urlEncoding('post_details')}/<str:post_id>/", post_detail, name='post_detail'),
    path(f"{urlEncryption('search')}{urlEncoding('search')}/", search_results, name='search_results'),
    path(f"{urlEncryption('graph_anaylsis')}{urlEncoding('graph_anaylsis')}/<str:post_id>/", graphAnalysis, name='graph_anaylsis'),
    path(f"{urlEncryption('help')}{urlEncoding('help')}/", help, name='help'),
    path(f"{urlEncryption('comparison')}{urlEncoding('comparison')}/", usersComparison, name='comparison'),
    # path(f"{urlEncryption('export_data')}{urlEncoding('export_data')}/", export_data, name='export_data'),
    path(f"{urlEncryption('export_data')}{urlEncoding('export_data')}/", export_data_json, name='export_data_json'),
    path(f"{urlEncryption('compare_users')}{urlEncoding('compare_users')}/", compare_users, name='compare_users'),
    path(f"{urlEncryption('kill_switch')}{urlEncoding('kill_switch')}/<str:post_id>/", kill_switch, name='kill_switch'),
]

dashboard/models.py
from django.db import models
import uuid

MEDIA_CHOICES = (
    ('Textual', 'Textual'),
    ('Photographic', 'Photographic'),
    ('Video', 'Video'),
    ('Audio', 'Audio'),
    ('Live', 'Live'),
)

class SocialMediaPlatform(models.Model):
    logo = models.ImageField(upload_to="images/")
    name = models.CharField(max_length=50)
    domain_name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    api_key = models.CharField(max_length=150)
    api_secret = models.CharField(max_length=150)
    access_token = models.CharField(max_length=150)
    access_token_secret = models.CharField(max_length=50)
    created_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

class Country(models.Model):
    abbr = models.CharField(max_length=3)

    def __str__(self):
        return self.abbr

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    platform = models.ForeignKey(SocialMediaPlatform, on_delete=models.CASCADE)
    username = models.CharField(max_length=255)
    post_id = models.CharField(max_length=255, unique=True)
    likes = models.JSONField(default=list)
    num_comments = models.JSONField(default=list)
    shares = models.JSONField(default=list)
    post_date = models.DateField()
    content = models.TextField()
    user_provided_id = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now=True)
    positive_score = models.FloatField(default=0.0)
    neutral_score = models.FloatField(default=0.0)
    bad_score = models.FloatField(default=0.0)
    frequency = models.IntegerField(default=0)
    comments = models.JSONField(default=list)  # Assuming comments are stored as a JSON list
    likes_growth_rates = models.JSONField(default=list)
    shares_growth_rates = models.JSONField(default=list)
    num_comments_growth_rates = models.JSONField(default=list)
    switch_status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.username} {self.post_id}"

dashboard/forms.py
from django import forms
from django.core.validators import MinValueValidator
from .widgets import JSONWidget

class EditForm(forms.Form):
  frequency = forms.IntegerField(required=True, validators=[MinValueValidator(0)])
class NewPostManuallyForm(forms.Form):
  OPTIONS1 = [
      ('Facebook', 'Facebook'),
      ('Twitter', 'Twitter'),
      ('Linkedin', 'Linkedin'),
      ('TikTok', 'TikTok'),
      ('Instagram', 'Instagram'),
      ('Youtube', 'Youtube'),
  ]

  OPTIONS2 = [
      ('Text', 'Text'),
      ('Picture', 'Picture'),
      ('Video', 'Video'),
  ]

  platform_id = forms.ChoiceField(choices=OPTIONS1)
  post_date = forms.DateField(label='Date')
  user_id = forms.CharField(max_length=255, required=True)
  username = forms.CharField(max_length=255, required=True)
  content_type = forms.ChoiceField(choices=OPTIONS2)
  content = forms.CharField(widget=forms.Textarea(), required=True)
  url = forms.URLField(widget=forms.TextInput(), required=True)
  post_id = forms.CharField(max_length=255, required=True)
  likes = forms.IntegerField(required=True, validators=[MinValueValidator(0)])
  shares = forms.IntegerField(required=True, validators=[MinValueValidator(0)])
  num_comments = forms.IntegerField(required=True, validators=[MinValueValidator(0)])
  comments = forms.JSONField()
    
class AddForm(forms.Form):
  OPTIONS1 = [
      ('Facebook', 'Facebook'),
      ('Twitter', 'Twitter'),
      ('Linkedin', 'Linkedin'),
      ('TikTok', 'TikTok'),
      ('Instagram', 'Instagram'),
      ('Youtube', 'Youtube'),
  ]
  OPTIONS = [
      ('Text', 'Text'),
      ('Picture', 'Picture'),
      ('Video', 'Video'),
  ]

  platform_id = forms.ChoiceField(choices=OPTIONS1)
  user_id = forms.CharField(max_length=255, required=True)
  username = forms.CharField(max_length=255, required=True)
  content_type = forms.CharField(max_length=255, required=True )
  content = forms.CharField(widget=forms.Textarea(), required=True)
  url = forms.URLField(widget=forms.TextInput(), required=True)
  post_id = forms.CharField(max_length=255, required=True)
  likes = forms.IntegerField(required=True, validators=[MinValueValidator(0)])
  shares = forms.IntegerField(required=True, validators=[MinValueValidator(0)])
  num_comments = forms.IntegerField(required=True, validators=[MinValueValidator(0)])
    

dashboard/views.py
from math import ceil
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from django.utils.dateparse import parse_datetime

from .utils import get_social_media_platform
from .models import Post  # Import your Post model
from .forms import *
from .scrapper.fb_scrap import FacebookScrapper
from .scrapper.twitter_scrap import TwitterScrapper
from .scrapper.linkedin_scrap import LinkedinScrapper
from .scrapper.sentiments import analyze_sentiments

import datetime
import uuid
import facebook_scraper
import urllib.parse

@login_required(login_url='signin')
def main(request):
    # Retrieve data from PostgreSQL using Django ORM
    posts = Post.objects.all().order_by('-last_updated')

    paginator = Paginator(posts, 50)  # Display 50 items per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver the last page of results.
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts
    }
    return render(request, 'dashbase.html', context)

def find_related_usernames(username):
    posts = Post.objects.all()
    all_usernames = [post.username for post in posts]
    matching_usernames = []
    substrings = []
    split_names = username.split(",")

    for name in split_names:
        substrings.append(name.replace(" ", "_"))
        substrings.append(name.replace("_", " "))
        substrings.append(name.upper())
        substrings.append(name.lower())
        substrings.append(name.title())
        substrings.extend(name.split(" "))

    for substring in substrings:
        for word in all_usernames:
            if substring in word:
                matching_usernames.append(word)

    return matching_usernames

@login_required(login_url='signin')
def search_results(request):
    try:
        username = request.GET.get('username')
        likes = request.GET.get('likes')
        comments = request.GET.get('comments')
        shares = request.GET.get('shares')
        post_date = request.GET.get('post_date')

        query = Post.objects.all()
        matching_usernames = find_related_usernames(username)
        matching_usernames = list(set(matching_usernames))

        if username:
            query = query.filter(username__in=matching_usernames)
        
        if likes:
            likes = int(likes)
            if likes > 0:
                query = query.filter(likes__value__lte=likes)
        
        if comments:
            comments = int(comments)
            if comments > 0:
                query = query.filter(num_comments__value__lte=comments)
        
        if shares:
            shares = int(shares)
            if shares > 0:
                query = query.filter(shares__value__lte=shares)
        
        if post_date:
            query = query.filter(post_date=datetime.strptime(post_date, '%Y-%m-%d').date())

        results = query
        context = {'results': results}
        paginator = Paginator(results, 5)  # Display 5 items per page
        page = request.GET.get('page')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            results = paginator.page(paginator.num_pages)

        if not results:
            messages.info(request, "There are no results for your search query.")

        return render(request, 'search_post.html', context)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)

@login_required(login_url='signin')
def new_post_manually(request):
    posts = Post.objects.all().order_by('-last_updated')
    paginator = Paginator(posts, 50)  # Display 50 items per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts}
    if request.method == 'POST':
        form = NewPostManuallyForm(request.POST)
        if form.is_valid():
            post_data = form.cleaned_data
            platform = get_social_media_platform(post_data['platform_id'])
            comments = []
            for comment in post_data['comments']:
                comments.append(comment['comment_text'])

            sentiment_results = analyze_sentiments(comments)
            now_str = datetime.datetime.now().isoformat()

            new_post = Post(
                id=uuid.uuid4(),
                platform=platform,
                username=post_data['username'],
                post_id=post_data['post_id'],
                likes=[{'value': post_data['likes'], 'timestamp': now_str}],
                num_comments=[{'value': post_data['num_comments'], 'timestamp': now_str}],
                shares=[{'value': post_data['shares'], 'timestamp': now_str}],
                post_date=post_data['post_date'],
                content=post_data['content'],
                user_provided_id=post_data['post_id'],
                comments=post_data['comments'],
                likes_growth_rates=[],
                shares_growth_rates=[],
                num_comments_growth_rates=[],
                positive_score=sentiment_results["good"],
                neutral_score=sentiment_results["neutral"],
                bad_score=sentiment_results["bad"],
                frequency=0,
                switch_status=False,
            )
            new_post.save()

            messages.info(request, f"{new_post.username}'s post metrics with ID {new_post.post_id} inserted successfully.")
            return redirect('main')
    else:
        form = NewPostManuallyForm(initial={'user_id': 'None'})

    context['form'] = form
    return render(request, 'new_post_manually.html', context)


@login_required(login_url='signin')
def newPost(request):
    if request.method == 'POST':
        context = {}
        scrapped_result = None
        pid = request.POST['post_id']
        platform = request.POST['platform']
        frequency = request.POST['frequency']
        username = request.POST.get('linkedin_username', None)

        try:
            if platform == 'Facebook':
                check_existing = Post.objects.filter(user_provided_id=pid, platform_id='1').first()
                scrapped_result = FacebookScrapper(pid, check_existing) if check_existing else FacebookScrapper(pid)
                scrapped_result['frequency'] = int(frequency) * 3600

            elif platform == 'Twitter':
                check_existing = Post.objects.filter(user_provided_id=pid, platform_id='2').first()
                scrapped_result = TwitterScrapper(pid, check_existing) if check_existing else TwitterScrapper(pid)
                scrapped_result['frequency'] = int(frequency) * 3600

            elif platform == 'LinkedIn':
                check_existing = Post.objects.filter(user_provided_id=pid, platform_id='3').first()
                scrapped_result = LinkedinScrapper(pid, username, check_existing) if check_existing else LinkedinScrapper(pid, username)
                scrapped_result['frequency'] = int(frequency) * 3600

            context = {'scrapped_result': scrapped_result}

        except facebook_scraper.exceptions.InvalidCookies as e:
            messages.info(request, f"{e} for Facebook")
            return redirect('new_post')

        except facebook_scraper.exceptions.TemporarilyBanned as e:
            messages.info(request, f"{e} from Facebook")
            return redirect('new_post')

        except facebook_scraper.exceptions.AccountDisabled as e:
            messages.info(request, f"{e} from Facebook")
            return redirect('new_post')

        except facebook_scraper.exceptions.NotFound as e:
            messages.info(request, f"{e} or maybe check if you scrapped the wrong social media platform.")
            return redirect('new_post')

        except IndexError as e:
            messages.info(request, f"{e} or maybe check if you scrapped the wrong social media platform.")
            return redirect('new_post')

        if username:
            scrapped_result['linkedin_username'] = username

        request.session['scrapped_result'] = scrapped_result

        return render(request, 'new_post.html', context)

    return render(request, 'new_post.html')

@login_required(login_url='signin')
def savePost(request, post_id):
    scrapped_result = request.session.get('scrapped_result')
    existing_post = Post.objects.filter(user_provided_id=post_id).first()
    
    if existing_post:
        for key, value in scrapped_result.items():
            setattr(existing_post, key, value)
        existing_post.last_updated = datetime.now()
        existing_post.save()
        messages.info(request, f"{existing_post.username}'s post metrics with ID {post_id} updated successfully.")
    else:
        new_post = Post(**scrapped_result)
        new_post.id = uuid.uuid4()
        new_post.last_updated = datetime.now()
        new_post.save()
        messages.info(request, f"{new_post.username}'s post metrics with ID {post_id} inserted successfully.")
    
    comments = [comment['comment_text'] for comment in new_post.comments]
    sentiment_results = analyze_sentiments(comments)
    new_post.positive_score = sentiment_results['good']
    new_post.neutral_score = sentiment_results['neutral']
    new_post.bad_score = sentiment_results['bad']
    new_post.save()

    del request.session['scrapped_result']
    return redirect('main')

def post_life_span(post_id):

dashboard/templates/add_post.html
{% extends 'dashbase.html' %}
{% block content %}

<!-- my_form.html -->
<div class="preview-post-container">
    <div class="form-title">Add Manual Entry</div>
    <form method="POST">
        {% csrf_token %}
        <div class="form-field">
            {{ form.as_p }}
        </div>
        <button class="add-button" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

dashboard/templates/comparison.html
{% extends 'dashbase.html' %} {% block content %}
<div class="home-alert">{% include 'includes/alerts.html' %}</div>
<!-- my_form.html -->
<form class="form" method="POST" action="{% url 'comparison' %}">
  {% csrf_token %}
  <div class="form-title">Compare users</div>
  <div class="form-field">
    <label for="username1">First username:</label>
    <select name="username1" id="username1" required>
      {% for username in all_usernames%}
      <option>{{username}}</option>
      {% endfor%}
    </select>
  </div>
  <div class="form-field">
    <label for="username2">Second username:</label>
    <select name="username2" id="username2" required>
      {% for username in all_usernames%}
      <option>{{username}}</option>
      {% endfor%}
    </select>
  </div>
  <button class="test-scrap-button" type="submit" target="_blank">
    Send to voyager
  </button>
</form>
{% endblock %}

dashboard/templates/edit_post.html
{% extends 'dashbase.html' %}
{% block content %}
<div style="margin: 20px;">

    <!-- my_form.html -->
    <div class="preview-post-container">
        <div class="form-title">Edit Post Frequency</div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-field">
                <label for="frequency">Frequency in hrs:</label>
                <input type="number" min="0" step="1" placeholder="eg 1" name="frequency" required />
            </div>
            <button class="save-update-button" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

dashboard/templates/help.html
{% extends 'dashbase.html' %} {% block content %}
<div class="help-container">
  <div class="title">Social Listener Features</div>
  <div>
    <div class="doc">
      <div class="doc_content" style="padding-left: 20px">
        <ul>
          <li><a href="#post-page" style="color: black;">Post Page</a></li>
          <li><a href="#post-detail" style="color: black;">Post Detail View Page</a></li>
          <li><a href="#new-post" style="color: black;">New Post to Track</a></li>
          <li><a href="#add-entry" style="color: black;">Add entry Manually</a></li>
          <li><a href="#edit-post" style="color: black;">Edit entry Manually</a></li>
        </ul>
      </div>
      <div class="doc_body">
        <div class="page">
          <h3 style="margin-top: 40px; margin-left: 0px !important">Post Page</h3>
          <div class="page-description" id="post-page">
            <p>
              All Social Media posts which are being tracked would be shown here.
            </p>
            <p>
              User can also filter or search posts based upon different filters
              i.e. username, likes, post date etc.
            </p>
            <p>Searching Metrics:</p>
            <dl style="padding-left: 20px">
              <ol type="1">
                <li>
                  <dt style="font-weight: 700;">Usernames:</dt>
                  <dd>
                    A user can easily filter out the posts based upon the
                    username. The powerful search engine also allows the user to
                    search posts from multiple users at the same time using comma
                    separated values.
                  </dd>
                </li>
                <li>
                  <dt style="font-weight: 700;">Number of likes:</dt>
                  <dd>
                    Posts can also be categorized based upon the number of likes.
                    One can easily provide the range of likes to filter out the
                    posts.
                  </dd>
                </li>
                <li>
                  <dt style="font-weight: 700;">Number of comments:</dt>
                  <dd>
                    Number of comments can also be used to filter out the posts.
                  </dd>
                </li>
                <li>
                  <dt style="font-weight: 600;">Number of shares:</dt>
                  <dd>
                    Another metric is the number of shares which can be used to
                    easily filter out the posts.
                  </dd>
                </li>

                <li>
                  <dt style="font-weight: 700;">Post date:</dt>
                  <dd>
                    Last metric is the post date which provides convinience to the
                    user to filter out the posts based upon the post date.
                  </dd>
                </li>
              </ol>
            </dl>
            <p>
              Also in addition, one can use all of these filters at the same time
              to do more robust search.
            </p>

            <p>
              Each post displays the metrics which could be used to analyze the
              overall engagement on any social media post. That includes the no.
              of likes, comments, shares and overall sentiment of the comments on
              that post.
            </p>
            <p>For each post, a user can have the following interactions:</p>
            <dl>
              <ol type="a" style="padding-left: 20px">
                <li>
                
                    The user can view the post details by clicking on the post
                  
                </li>
                <li>

                  The user can capture the data manually for the post.It allows
                  the user to add data manually just in case scrapper stops
                  working or would like to enter post metadata manually on an
                  ad-hoc basis
                </li>
                <li>
                 
                    It allows to manually edit the data for the post. For now one
                    can edit the frequency (the time the scrapper will take to
                    extract updated metrics).
                  
                </li>
                <li>
                  
                    The user can delete any post from the system at any time after
                    the confirmation.
                 
                </li>
              </ol>
            </dl>
          </div>
        </div>
        <div class="page">
          <h3 style="margin-top:40px;margin-left: 0px !important">New Post to Track</h3>
          <div class="page-description" id="new-post">
            <p>Here, the user can add a new post to track in the system.</p>
            <p>
              The user is required to provide the POST ID, Social Media platform,
              and frequency of the scrapper to add new post in the system.
            </p>
            <p>
              The system provides an additional feature to test scrapper before
              the user add any post to track. The user can test the scrapper to
              see if it is working fine or not.
            </p>
            <p>
              A unique ID is generated with each post which could help to search
              posts from the DB.
            </p>
          </div>
        </div>
        <div class="page">
          <h3 style="margin-top:40px;margin-left: 0px !important">Add Entry Manually</h3>
          <div class="page-description" id="add-entry">
            <p>A user can also manually add data of any specific post in the system.
              For this, the user is required to provide the following information:</p>
            </p>
            <p>Example:</p>
            <ol style="padding-left: 20px">
              <li>Number of likes</li>
              <li>Number of shares</li>
              <li>Comments etc</li>
            </ol>
          </div>
        </div>
        <div class="page">
          <h3 style="margin-top:40px;margin-left: 0px !important">Edit Entry Manually</h3>
          <div class="page-description" id="edit-post">
            <p>
              In the Posts page, all the available posts that are been tracked are
              shown here.
            </p>
            <p>
              The search engine is powerful in a way that one is allowed to search
              for posts by different criteria that are connected to the post.
            </p>
            <p>Example:</p>
            <ol style="padding-left: 20px">
              <li>Usernames</li>
              <li># of likes</li>
              <li># of comments</li>
              <li>date</li>
              <li># of likes</li>
              <li># of comments</li>
            </ol>
          </div>
        </div>
        <div class="page">
          <h3 style="margin-top:40px;margin-left: 0px !important">Post Detail View Page</h3>
          <div class="page-description" id="post-detail">
            <p>The page should you:</p>
            <ol style="padding-left: 20px">
              <li>the date of the Post</li>
              <li>URL to the Post</li>
              <li>the content itself</li>
              <li>graphs with time series</li>
              <li>
                the unique ID generated based on static metrics, and that would
                serve as an index for fast search
              </li>
            </ol>
            <p>Metrics shown in the graph are:</p>
            <ol style="padding-left: 20px">
              <li>number of likes</li>
              <li>number of shares</li>
              <li>number of comments</li>
              <li>sentiment analysis of comments</li>
              <li>media type e.g. if the Post is an image/video</li>
              <li>Post’s longevity e.g. time it took for the post to “die”</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.getElementById("tpContainer").style.display = "none";
    document.getElementById("searchContainer").style.display = "none";
  });
</script>
{% endblock %}

dashboard/templates/new_post_manually.html
{% extends 'dashbase.html' %}
{% block content %}

<!-- my_form.html -->
<div class="preview-post-container">
    <div class="form-title">New Post Manual Entry</div>
    <form method="POST" action="{% url 'new_post_manually' %}">
        {% csrf_token %}
        <div class="form-field">
            {{ form.as_p }}
            <script>
                $(document).ready(function() {
                    $("#id_post_date").datepicker();
                });
            </script>
        </div>
        <button class="add-button" type="submit">Submit</button>
    </form>
</div>
{% endblock %}